name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java file
        run: javac demo.java

      - name: Create JAR
        run: |
          echo "Main-Class: demo" > manifest.txt
          echo "" >> manifest.txt
          jar cfm demo.jar manifest.txt demo.class

      - name: Run JAR
        run: java -jar demo.jar
